In [71]:
class Simple_linear_regression():
    def __init__(self):
        self.m=None
        self.b=None
    
    def fit(self,x_train,y_train):
        if isinstance(x_train, pd.DataFrame) or isinstance(x_train, pd.Series):
            x_train = x_train.to_numpy()
        if isinstance(y_train, pd.DataFrame) or isinstance(y_train, pd.Series):
            y_train = y_train.to_numpy()
        num=0
        den=0
        for i in range(x_train.shape[0]):
            num=num+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den=den+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))
        self.m=num/den
        self.b=y_train.mean()-(self.m*x_train.mean())
    def predict(self,x_test):
        if isinstance(x_test, pd.DataFrame) or isinstance(x_test, pd.Series):
            x_test = x_test.to_numpy()
        return self.m*x_test+self.b

In [72]:
import numpy as np
import pandas as pd

df=pd.read_csv('placement.csv')
df.head(5)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [73]:
from sklearn.model_selection import train_test_split
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train

     cgpa
79   7.18
197  7.21
38   8.62
24   6.53
122  5.12
..    ...
106  6.13
14   7.73
92   7.90
179  7.14
102  5.13

[160 rows x 1 columns]

In [74]:
x_test

     cgpa
95   6.63
15   7.25
30   7.36
158  5.95
128  7.93
115  8.35
69   7.30
170  6.22
174  7.32
45   7.87
66   5.11
182  5.88
165  8.21
78   6.59
186  7.84
177  7.09
56   5.84
152  7.37
82   5.58
68   7.56
124  6.06
16   6.84
148  7.57
93   6.79
65   7.60
60   5.61
84   4.26
67   6.51
125  7.33
132  5.84
9    8.31
18   6.94
55   8.20
75   6.97
150  6.30
104  7.62
135  6.10
137  7.14
164  9.06
76   6.94

In [75]:
y_test

95     2.79
15     3.23
30     3.26
158    3.04
128    3.34
115    4.21
69     2.94
170    2.87
174    2.99
45     3.58
66     1.63
182    2.08
165    4.08
78     2.21
186    3.47
177    3.64
56     2.74
152    3.08
82     2.17
68     2.99
124    2.31
16     2.35
148    3.40
93     3.08
65     3.81
60     2.19
84     1.53
67     2.89
125    3.16
132    2.48
9      3.51
18     2.98
55     3.39
75     3.28
150    2.73
104    3.74
135    2.60
137    3.13
164    3.82
76     3.15
Name: package, dtype: float64

In [80]:
slr=Simple_linear_regression()
slr.fit(x_train,y_train)
slr.predict(x_test)

array([[2.78031348],
       [3.13635249],
       [3.1995207 ],
       [2.38981908],
       [3.52684689],
       [3.76803461],
       [3.16506531],
       [2.54486832],
       [3.17655044],
       [3.4923915 ],
       [1.90744364],
       [2.34962112],
       [3.6876387 ],
       [2.75734322],
       [3.47516381],
       [3.04447145],
       [2.32665086],
       [3.20526327],
       [2.17734418],
       [3.314372  ],
       [2.45298729],
       [2.90090734],
       [3.32011456],
       [2.87219451],
       [3.33734226],
       [2.19457187],
       [1.41932564],
       [2.7114027 ],
       [3.18229301],
       [2.32665086],
       [3.74506435],
       [2.95833298],
       [3.68189614],
       [2.97556068],
       [2.59080884],
       [3.34882738],
       [2.47595755],
       [3.07318428],
       [4.17575671],
       [2.95833298]])

In [78]:
###Form scikit learn library
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
lr.predict(x_test)

array([2.78031348, 3.13635249, 3.1995207 , 2.38981908, 3.52684689,
       3.76803461, 3.16506531, 2.54486832, 3.17655044, 3.4923915 ,
       1.90744364, 2.34962112, 3.6876387 , 2.75734322, 3.47516381,
       3.04447145, 2.32665086, 3.20526327, 2.17734418, 3.314372  ,
       2.45298729, 2.90090734, 3.32011456, 2.87219451, 3.33734226,
       2.19457187, 1.41932564, 2.7114027 , 3.18229301, 2.32665086,
       3.74506435, 2.95833298, 3.68189614, 2.97556068, 2.59080884,
       3.34882738, 2.47595755, 3.07318428, 4.17575671, 2.95833298])